### ISSUE TITLE
Does it work with sound effect in KH2 PC ?

### ISSUE THREAD

**Issue by Fotia13** [Leinxad/KHPCMusicTools#1]
Hello I have tried to replace some sound effect in KH2FM PC with the MultiEncoder, so I have all the tracks (19) to replace in the same folder (image
![Help multiencoder sound effect](https://user-images.githubusercontent.com/81991499/128641303-aadc5fff-cc12-49b3-8634-ea19122fb089.jpg)
)

All my WAV files work and are in signed 16-bit PCM. The 1.wav don't have metadatas.

When I try to put it in MultiEncoder I have this error:

```
D:\KH related\Modding\Application\For Sound\KHPCMusicTools\MultiEncoder>MultiEncoder.exe se560.scd
Opening with wav module: WAV file reader
Encoding "D:\KH related\Modding\Application\For Sound\KHPCMusicTools\MultiEncoder\1.wav" to
         "D:\KH related\Modding\Application\For Sound\KHPCMusicTools\MultiEncoder\1.ogg"
at quality 10,00
        [ 97,6%] [ 0m00s remaining] |

Done encoding file "D:\KH related\Modding\Application\For Sound\KHPCMusicTools\MultiEncoder\1.ogg"

        File length:  0m 00,0s
        Elapsed time: 0m 01,0s
        Rate:         0,8301
        Average bitrate: 455,4 kb/s

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MultiEncoder.Program.<Main>g__OGGtoSCD|1_1(Byte[] wav, Byte[] entry, String oggPath, Int32 LoopStart_Sample, Int32 Total_Samples) in C:\Users\Leinxad\Documents\KHModding\KHPCMusicTools\MultiEncoder\Program.cs:line 119
   at MultiEncoder.Program.Main(String[] args) in C:\Users\Leinxad\Documents\KHModding\KHPCMusicTools\MultiEncoder\Program.cs:line 69

D:\KH related\Modding\Application\For Sound\KHPCMusicTools\MultiEncoder>
```

So is it possible to use the musictools for sound effect ? If yes, can you help me with this error ?

**Comment by Leinxad** [comment]
Hi, Sound effects are msadpcm scd, music tools only supports ogg scd, so they dont work with sound effects, i think that with noxalus tools you should be able to replace sound effects.

**Comment by Fotia13** [comment]
Okay thanks a lot
